# Site settings
title: Fabíola Nogueira - Make Up
email: gnfabiola@gmail.com
phone: (45) 9985-6510
description: > # this means to ignore newlines until "baseurl:"
  Fabíola Nogueira - Make Up. Make up, Maquiagem, Cabelo, Fotos, Casamentos.
baseurl: "fabiolanogueira/" # the subpath of your site, e.g. /blog/
url: "http://thiagofesta.com" # the base hostname & protocol for your site
fullurl: "http://thiagofesta.com/fabiolanogueira/"
facebook_username: FabiolaNogueiraMakeUpStudio

# Build settings
markdown: kramdown

#APIs
simple_form_key: 7c0199bc3fccf0f945164a6d49651934

